-- Ejecutar en Supabase > SQL Editor
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  seller_id uuid not null,
  buyer_id uuid not null,
  buyer_name text not null,
  buyer_phone text not null,
  buyer_address text not null,
  product_id bigint not null,
  product_title text not null,
  quantity integer not null check (quantity > 0),
  total numeric(12, 2) not null check (total >= 0),
  whatsapp_url text,
  notification_type text not null default 'seller_order',
  status text not null default 'unread',
  created_at timestamptz not null default now()
);

alter table public.notifications
add column if not exists notification_type text not null default 'seller_order';

alter table public.notifications enable row level security;

drop policy if exists "Compradores pueden crear notificaciones" on public.notifications;
create policy "Compradores pueden crear notificaciones"
on public.notifications
for insert
to authenticated
with check (auth.uid() = buyer_id);

drop policy if exists "Vendedores pueden ver sus notificaciones" on public.notifications;
create policy "Vendedores pueden ver sus notificaciones"
on public.notifications
for select
to authenticated
using (auth.uid() = seller_id);

grant select, insert on public.notifications to authenticated;
grant update on public.notifications to authenticated;

drop policy if exists "Usuarios pueden marcar sus notificaciones" on public.notifications;
create policy "Usuarios pueden marcar sus notificaciones"
on public.notifications
for update
to authenticated
using (auth.uid() = seller_id or auth.uid() = buyer_id)
with check (auth.uid() = seller_id or auth.uid() = buyer_id);